# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cb7f84ae33b7765643ccf73d780fda8a2a157cf8dfa4f792e85a3721acdae748fb9e5147b1b8b3cc0dead4843ee9677ca0c6af24604ba2e85c0b5f990f0f66b

test:
  secret_key_base: df54ba7e6677f0b066f673a86669896f1353d8ad1f99b27a683c750f715026f29410102650b570d61f677836d2aec21ba6f64a6e24cdc70ced9b08a5496834d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
